version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 7777:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: local_user
      POSTGRES_USER: local_user
      POSTGRES_DB: local_db